service: apollo-lambda
provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-offline
functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: index.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
      - http:
          path: graphql
          method: get